### ISSUE TITLE
This is a warning to you, from GalacticFantasy#0001, You are being targeted from hackers off the dark web, other hackers, and the discord officials to get banned from discord. You have messed up

### ISSUE THREAD

**Issue by AnonymousMonke12** [jona939s/XXXL-ARMS#3]
This is a warning to you, from GalacticFantasy[#0001](https://www.youtube.com/hashtag/0001), You are being targeted from hackers off the dark web, other hackers, and the discord officials to get banned from discord. You have messed up

**Comment by jona939s** [comment]
:D
